services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.web
    ports:
      - "3000:80"
    depends_on:
      - cors-proxy
      - token-server
    restart: unless-stopped

  cors-proxy:
    build:
      context: ./web
      dockerfile: Dockerfile.proxy
    env_file:
      - .env
    ports:
      - "3002:3002"
    restart: unless-stopped

  token-server:
    build:
      context: ./web
      dockerfile: Dockerfile.token
    env_file:
      - .env
    ports:
      - "3007:3007"
    restart: unless-stopped
