FROM nginx:alpine
COPY . /usr/share/nginx/html
COPY nginx.conf.template /etc/nginx/templates/default.conf.template
ENV CORS_PROXY_HOST=cors-proxy
ENV TOKEN_SERVER_HOST=token-server
ENV WEB_PORT=80
EXPOSE 80
